application: angular-seed
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Angular application.
- url: /
  static_files: static/app/index.html
  upload: static/app/index.html
  secure: always

# Angular application files.
- url: /app
  static_dir: static/app
  secure: always

# Application test files.
- url: /test
  static_dir: static/test
  secure: always

# Cloud Endpoints handler. 
- url: /_ah/spi/.*
  script: services.app
  secure: always